const dummyWallets = [
  {
    id: 1,
    userId: 1,
    name: "Main Wallet",
    balance: 500000,
  },
  {
    id: 2,
    userId: 2,
    name: "Savings Account",
    balance: 1200000,
  },
  {
    id: 3,
    userId: 3,
    name: "Cash Wallet",
    balance: 200000,
  },
];

const dummyBudgets = [
  {
    id: 1,
    userId: 1,
    name: "Monthly Groceries",
    limit: 300000,
  },
  {
    id: 2,
    userId: 1,
    name: "Transport Expenses",
    limit: 150000,
  },
  {
    id: 3,
    userId: 2,
    name: "Entertainment Budget",
    limit: 250000,
  },
  {
    id: 4,
    userId: 3,
    name: "Health & Wellness",
    limit: 500000,
  },
];

const dummyExpenses = [
  {
    id: 1,
    userId: 1,
    walletId: 1,
    budgetId: 1,
    category: "food",
    description: "Groceries",
    amount: 20000,
    createdAt: "2021-09-01",
    wallet: dummyWallets.find((w) => w.id === 1),
    budget: dummyBudgets.find((b) => b.id === 1),
  },
  {
    id: 2,
    userId: 1,
    walletId: 1,
    budgetId: 2,
    category: "transportation",
    description: "Gas refill",
    amount: 50000,
    createdAt: "2021-09-05",
    wallet: dummyWallets.find((w) => w.id === 1),
    budget: dummyBudgets.find((b) => b.id === 2),
  },
  {
    id: 3,
    userId: 2,
    walletId: 2,
    budgetId: 3,
    category: "entertainment",
    description: "Movie tickets",
    amount: 75000,
    createdAt: "2021-09-10",
    wallet: dummyWallets.find((w) => w.id === 2),
    budget: dummyBudgets.find((b) => b.id === 3),
  },
  {
    id: 4,
    userId: 1,
    walletId: 1,
    budgetId: 4,
    category: "healthcare",
    description: "Doctor consultation",
    amount: 120000,
    createdAt: "2021-09-12",
    wallet: dummyWallets.find((w) => w.id === 1),
    budget: dummyBudgets.find((b) => b.id === 4),
  },
  {
    id: 5,
    userId: 3,
    walletId: 3,
    budgetId: 2,
    category: "personal_care",
    description: "Haircut",
    amount: 45000,
    createdAt: "2021-09-15",
    wallet: dummyWallets.find((w) => w.id === 3),
    budget: dummyBudgets.find((b) => b.id === 2),
  },
  {
    id: 6,
    userId: 2,
    walletId: 2,
    budgetId: 4,
    category: "gifts_donations",
    description: "Charity donation",
    amount: 100000,
    createdAt: "2021-09-20",
    wallet: dummyWallets.find((w) => w.id === 2),
    budget: dummyBudgets.find((b) => b.id === 4),
  },
];

export { dummyExpenses, dummyWallets, dummyBudgets };
